file(READ "${GLSL_FILE}" _content)
string(REPLACE "\r" "" _norm "${_content}")
file(WRITE "${GLSL_HDR}"
"// Generated by CMake - DO NOT EDIT
// Source: ${GLSL_FILE}
#pragma once
namespace shaders {
inline constexpr const char *${GLSL_SYMBOL} = R\"GLSL(${_norm})GLSL\";
} // namespace shaders
")
